config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: %i[create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = %w[chinese italian japanese french belgian].freeze
  validates :category, inclusion: { in: CATEGORIES }
  validates :name, :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = @restaurant.reviews.build
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save ? (redirect_to restaurant_path(@restaurant)) : (render :new)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save ? (redirect_to restaurant_path(@restaurant)) : (render 'restaurants/show')
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <ul class="list-unstyled">
    <% @restaurants.each do |restaurant| %>
      <li>
        <h3><%= link_to restaurant.name, restaurant_path(restaurant), style: "text-decoration: none;" %></h3>
        <p><%= restaurant.address %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>
  <%= simple_form_for [@restaurant] do |f| %>
    <%= f.input :name  %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Create Restaurant", class: "btn btn-secondary"  %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1>Restaurant</h1>
  raise
  <h3><% @restaurant.name %></h3>
  <h5><%= @restaurant.address %></h5>
  <p><%= @restaurant.phone_number %></p>
  <h5>Reviews:</h5>
  <ul class="list-unstyled">
    <% @restaurant.reviews.each do |review| %>
      <li>
        <% if review.persisted? %>
          <p><%= review.content %></p>
          <%= "⭐" * review.rating %>
          <%= link_to "Delete", review_path(review), data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
        <% end %>
      </li>
      <hr>
    <% end %>

  </ul>>
  <h1>New Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content  %>
    <%= f.input :rating %>
    <%= f.submit "Create Review", class: "btn btn-secondary"  %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content  %>
    <%= f.input :rating %>
    <%= f.submit "Create Review", class: "btn btn-secondary"  %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light border">
  <div class="container-fluid d-flex">
    <%= link_to "Restaurants", restaurants_path, class: "text-dark", style: "text-decoration: none;" %>
    <%= link_to "New Restaurant", new_restaurant_path, class: "text-dark", style: "text-decoration: none;" %>
  </div>
</nav>